### ISSUE TITLE
CRC error on STARTG2.png, 8x version (doom_sprfix_hires_8x)

### ISSUE THREAD

**Issue by r6d2** [kcghost/wadsnip#1]
Hi!

First of all, very interesting project, congrats!

As the title says, I'm getting a CRC error on the 8x version of STARTG2 texture, and image looks cut in half when opening it. Would you please try on your end to see if it also happens to you?

Thanks!

**Comment by kcghost** [comment]
Thanks for trying this out! I did notice a CRC error earlier so I took it down and remade/reuploaded. You might have grabbed it before I panicked and did that :). I no longer see a CRC error since reuploading. Could you try [redownloading](https://github.com/kcghost/wadsnip/releases/download/hires-v1.0/doom_sprfix_hires.zip) and let me know if you still see this issue?

**Comment by r6d2** [comment]
It's OK now, thanks!
